version: '3.1'
services:
  mariadb:
    image: mysql:5.7.26
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "qlalfqjsghekd"
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
